logging.level:
#  org.springframework.context: WARN
#  org.springframework.data: WARN
#  org.springframework.jdbc: WARN
#  example: DEBUG
  ROOT: INFO

spring:

  web:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

  kafka:
    streams:
      cache-max-size-buffering: 100
tanzu:
  governance:
    fips:
      # Disables the governance starter checks when tests are run
      exit-on-failure: false
management:
  endpoints:
    web:
      exposure:
        # Exposes the governance starter endpoint
        include: governance