logging.level:
#  org.springframework.context: WARN
#  org.springframework.data: WARN
#  org.springframework.jdbc: WARN
#  example: DEBUG
  ROOT: INFO

spring:

  web:
    locale: en_US

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true

  kafka:
    streams:
      state-store-cache-max-size: 100
tanzu:
  governance:
    fips:
      # Disables the governance starter checks when tests are run
      exit-on-failure: false
management:
  endpoints:
    web:
      exposure:
        # Exposes the governance starter endpoint
        include: governance
  endpoint:
    health:
      # [Spring Advisor]: This property disables health-group-membership-validation with boot 3.1 for backwards compatible reasons, but the Spring team encourages to enable it.

      validate-group-membership: false